[package]
name = "screenruster"
version = "0.1.0"
authors = ["meh. <meh@schizofreni.co>"]

[features]
default = ["auth-internal"]

auth-internal = []

[dependencies]
toml  = "0.1"
clap  = "2"
xdg   = "2"

libc  = "0.2"
dbus  = "0.3"

[dependencies.glium]
version          = "*"
default-features = false

[dependencies.x11]
version  = "2"
features = ["xlib", "glx"]
