[package]
name    = "api"
version = "0.1.0"

authors = ["meh. <meh@schizofreni.co>"]
license = "WTFPL"

[dependencies]
log  = "0.3"
toml = "0.1"

[dependencies.image]
version = "*"

[dependencies.glium]
version          = "*"
default-features = false
