[timer]
beat    = 10
timeout = 5
lock    = 0
cycle   = false
blank   = false

[auth]
use = ["internal"]

[auth.internal]
password = "test"

[saver]
use = ["laughing_man"]

[saver.laughing_man]
blur = true
