# X11 related settings.
[locker]
# The name of the display.
# display = ":0.0"

# Whether to take control of DPMS settings or not.
dpms = true

# What to do on suspension.
#
# - "ignore" will do nothing.
# - "use-system-time" will try to use system time to correct the monotonic
#   timers.
# - "activate" will activate the screen saver.
# - "lock" will lock the screen.
on-suspend = "use-system-time"

# DBus related settings.
[server]
# A list of types of messages to ignore.
#
# - "inhibit" will ignore screen saver inhibition requests.
# - "throttle" will ignore screen saver throttling requests.
# - "suspend" will ignore timer suspension requests.
#
# ignore = ["inhibit", "throttle"]

[timer]
# How many seconds to wait between each heartbeat.
#
# Heartbeats are used to sanitize X11 windows and other things.
beat = 10

# How many seconds to wait before starting the screen saver.
timeout = "5:00"

# How many seconds to wait before locking the screen after the screen saver has
# been started.
lock = false

# How many seconds to wait before blanking the screen.
#
# `false` makes it never blank.
blank = false

# General screen saver settings.
[saver]
# A list of screen savers to use.
use = ["laughing_man"]

# Whether to always throttle or not.
throttle = false

# Settings for a specific screen saver.
[saver.laughing_man]
blur = { max  = 1.2, step = 0.00001, count = 4 }
man  = { rotate = 0.000005, scale  = 400.0 }
